apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka-mils
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kafka
                  - key: zone
                    operator: In
                    values:
                    - stateful
      containers:
        - name: ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "http://my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://schema-registry-cp-schema-registry:8081"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: "kafka_connect_source"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: "http://kafka-connect-mssql-2019-source-cluster-connect-api:8083"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_1_NAME
              value: "kafka_connect_sink"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_1_ADDRESS
              value: "http://kafka-connect-gcs-sink-cluster-connect-api:8083"
         
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka-mils
  labels:
    app: kafka-ui
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kafka-ui